name: Deploy to Netlify

on:
  push:
    branches: [ main ]  # Adjust this if your default branch has a different name
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust this to match your project's Node version

    - name: List directory contents
      run: ls -la

    - name: Display package.json contents
      working-directory: ./nftrade-frontend
      run: cat package.json

    - name: Install dependencies
      working-directory: ./nftrade-frontend
      run: |
        npm cache clean --force
        npm install

    - name: Build
      working-directory: ./nftrade-frontend
      run: npm run build
      env:
        CI: false  # This prevents treating warnings as errors

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: './nftrade-frontend/build'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1
